spring:
  application:
    name: elm-food-server
  datasource:
    url: jdbc:mysql://localhost:3306/elm?useSSL=false&serverTimezone=UTC
    username: root
    password: Yb091864
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      enabled: false

server:
  port: 10200

mybatis:
  type-aliases-package: team.tjusw.elm.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:13000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
