server:
  port: 15001
spring:
  application:
    name: elm-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/ELM-CLOUD/elm-configs
#  rabbitmq:
##    host: 8.130.64.168
#    addresses: 8.130.64.168:5672
##    port: 5672
#    username: elm2
#    password: 111111
    
management:
  endpoints:
    web:
      exposure:
        include:
        - busrefresh
              
eurekahost1: 127.0.0.1 # 换成部署了该eureka server的主机的公网IP
eurekahost2: 127.0.0.1 #  换成部署了该eureka server的主机的公网IP
eureka:
  client:
    service-url:
      defaultZone: http://${eurekahost1}:13000/eureka/,http://${eurekahost2}:13000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
