logging:
  level:
    '[org.springframework]': debug
    '[team.tjusw.mapper]': debug
    '[org.springframework.boot.autoconfigure]': error

spring:
  application:
    name:   elm-point-server
  datasource:
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:elm2}?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: team.tjusw.po

