-- 创建 ELM 项目所需的数据库
CREATE DATABASE IF NOT EXISTS elm CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS elm2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 显示所有数据库
SHOW DATABASES;

-- 查看数据库字符集
SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
FROM information_schema.SCHEMATA
WHERE SCHEMA_NAME IN ('elm', 'elm2');
